#!/bin/bash

set -e

DIR="/home/ms/myp/problem-solving"

copy_file() {
    if [ -f "$1" ]; then
        echo "Already exists: $1"
    else
        cp "$DIR"/.stress-testing/"$1" "$PWD"
        echo "New file:       $1"
    fi
}

copy_file interactor.cpp
